//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace EvolveAPet
{
	[Serializable]
	public class Locus{
		private int _chromosome;
		private int _geneNumber;

		public int Chromosome{
			get{
				return _chromosome;
			}
		}

		public int GeneNumber{
			get{
				return _geneNumber;
			}
		}

		public Locus (int c, int g){
			_chromosome = c;
			_geneNumber = g;
		}
	}

	[Serializable]
	class LocusEqualityComparer : IEqualityComparer<Locus>{
		public bool Equals(Locus l1, Locus l2){
			return (l1.Chromosome == l2.Chromosome) && (l1.GeneNumber == l2.GeneNumber);
		}

		public int GetHashCode(Locus l)
		{
			int hCode = l.Chromosome ^ l.GeneNumber;
			return hCode.GetHashCode();
		}
	}
	
}
