//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace EvolveAPet
{
	public class Global
	{
		// Use this random to generate all random numbers in the whole program. C# random sucks otherwise if created in multiple classes.
		public static Random rand = new Random();
	}
}

